apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: surya-aws.tk/webapp:${BUILD_ID}
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8080
      imagePullSecrets:
        - name: secret
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - name: http
      port: 8080
      nodePort: 30020
  type: NodePort